# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e99d878a8b50a03904d9907d067170f891dbaa0311fb8298986d97c08dc755dfe587d3f915e2eb20b811ce8082c182a25d6292fca9167c1d42f0541b2797b9a

test:
  secret_key_base: 30abbba6ccb72dd34eed9ecfd2bd18c122371b120080114a7aa4b7c2774d65137316a5d7f8310908a88f12568c491d18b39bb98b8379a48c7d3eb828074ce76f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
